server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /liuyun-shiro

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/liuyun-shiro?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
  redis:
    database: 0
    host: 106.13.143.190
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 1
    timeout: 10000
    block-when-exhausted: true
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.liuyun.liuyunshiro.modules.pojo.enyity
  typeEnumsPackage: com.liuyun.liuyunshiro.modules.pojo.enums
# Logger Config
logging:
  level:
    com.liuyun.liuyunshiro.modules.mapper: debug

shiro:
  # Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
  cache:
    expire-time: 300
  # AccessToken过期时间-5分钟-5*60(秒为单位)
  access:
    token:
      expire-time: 300
  # RefreshToken过期时间-30分钟-30*60(秒为单位)
  refresh:
    token:
      expire-time: 1800
  # AES密码加密私钥(Base64加密)
  encryptAESKey: TGl1WXVuU2hpcm9Tb3VsMDkyOA==
  # JWT认证加密私钥(Base64加密)
  encryptJWTKey: U291bDA5MjhMaXVZdW5TaGlybw==


